backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

#publish_mode: editorial_workflow # Only include if you want an interface for drafting, reviewing, and approving posts

media_folder: 'static/images/uploads' # Media files will be stored in the repo under static/images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads

site_url: https://discussion.lttmagazine.co.uk
display_url: https://discussion.lttmagazine.co.uk
logo_url: '/local_transport_today_logo_colour.svg'

collections: # A list of collections the CMS should be able to edit
  - label: 'Pages'
    name: 'pages'
    format: 'json'
    extension: 'json'
    editor:
      preview: false
    files:
      - file: 'assets/content/pages/about.json'
        label: 'About'
        name: 'about'
        fields:
          - {label: 'Body', name: 'body', widget: 'markdown', required: true, buttons: ['bold', 'italic', 'link', 'heading-three', 'bulleted-list', 'numbered-list'], editor_components: []}
  - name: 'settings'
    label: 'Settings'
    format: 'json'
    extension: 'json'
    editor:
      preview: false
    files:
      - file: 'assets/content/settings/home.json'
        label: 'Home Page'
        name: 'home'
        fields:
          - {label: 'Masthead', name: 'masthead', widget: 'select', required: true, multiple: false, default: "none", options: [{ label: "Hide Masthead", value: "none" }, { label: "Display Long Intro", value: "intro" }, { label: "Display Call-to-Action", value: "cta" }] }
          - label: "Long Intro"
            name: "intro"
            collapsed: true
            hint: "Use this to provide a long-form intro message."
            widget: "object"
            fields:
              - {label: 'Headline', name: 'headline', widget: 'string', required: false}
              - {label: 'Body', name: 'body', widget: 'markdown', required: false, buttons: ['bold', 'italic', 'link', 'heading-three', 'bulleted-list', 'numbered-list'], editor_components: []}
          - label: "Call-to-Action"
            name: "cta"
            collapsed: true
            hint: "Use this to provide a call-to-action to an event or video."
            widget: "object"
            fields:
              - {label: 'Headline', name: 'headline', widget: 'string', required: false}
              - {label: 'Sub-Headline', name: 'subHeadline', widget: 'string', required: false}
              - {label: 'Date', name: 'date', widget: 'datetime', required: false, default: "", format: 'YYYY-MM-DD', date_format: 'Do MMMM YYYY', time_format: false}
              - label: "Button"
                name: "button"
                collapsed: false
                hint: "Use this to provide a button for the call-to-action."
                widget: "object"
                fields:
                  - {label: 'URL', name: 'url', widget: 'string', required: false}
                  - {label: 'Text', name: 'text', widget: 'string', required: false}
                  - {label: 'Icon', name: 'icon', widget: 'select', required: false, multiple: false, default: "arrow", options: [{ label: "None", value: "" }, { label: "Arrow", value: "arrow" }, { label: "YouTube", value: "video" }] }
          #- {label: 'Featured Author', name: 'featuredAuthor', widget: 'relation', required: false, hint: 'Leave blank to disable this setting.', collection: 'authors', display_fields: ['name'], search_fields: ['name'], value_field: 'name', multiple: false, options_length: 20}
      #- file: 'assets/content/settings/header.json'
      #  label: 'Header'
      #  name: 'header'
      #  fields:
      #    - {label: 'Category 1', name: 'category1', widget: 'relation', required: false, hint: 'Leave blank to disable this setting.', collection: 'categories', display_fields: ['name'], search_fields: ['name'], value_field: 'name', multiple: false, options_length: 20}
      #    - {label: 'Category 2', name: 'category2', widget: 'relation', required: false, hint: 'Leave blank to disable this setting.', collection: 'categories', display_fields: ['name'], search_fields: ['name'], value_field: 'name', multiple: false, options_length: 20}
      #    - {label: 'Category 3', name: 'category3', widget: 'relation', required: false, hint: 'Leave blank to disable this setting.', collection: 'categories', display_fields: ['name'], search_fields: ['name'], value_field: 'name', multiple: false, options_length: 20}
      #    - {label: 'Category 4', name: 'category4', widget: 'relation', required: false, hint: 'Leave blank to disable this setting.', collection: 'categories', display_fields: ['name'], search_fields: ['name'], value_field: 'name', multiple: false, options_length: 20}
  - label: 'Authors'
    name: 'authors'
    folder: 'assets/content/authors'
    format: 'json'
    extension: 'json'
    create: true
    identifier_field: name
    preview_path: "/author/{{slug}}/"
    sortable_fields: ['name']
    editor:
      preview: false
    fields:
      - {label: 'Name', name: 'name', widget: 'string', required: true}
      - {label: 'Bio', name: 'bio', widget: 'string', required: true}
      - {label: 'Photo', name: 'photo', widget: 'image', allow_multiple: false, required: false}
      - {label: 'Email', name: 'email', widget: 'string', required: false}
      - {label: 'Website URL', name: 'website', widget: 'string', required: false, pattern: ['^(http|https)://', 'Please use the full URL (including the HTTPS)']}
      - {label: 'Twitter Page URL', name: 'twitter', widget: 'string', required: false, pattern: ['^(http|https)://', 'Please use the full URL (including the HTTPS)']}
      - {label: 'LinkedIn Page URL', name: 'linkedin', widget: 'string', required: false, pattern: ['^(http|https)://', 'Please use the full URL (including the HTTPS)']}
  - label: 'Categories'
    name: 'categories'
    folder: 'assets/content/categories'
    format: 'json'
    extension: 'json'
    create: true
    identifier_field: name
    preview_path: "/category/{{slug}}/"
    sortable_fields: ['name']
    editor:
      preview: false
    fields:
      - {label: 'Name', name: 'name', widget: 'string', required: true}
      #- {label: 'Featured Author', name: 'featuredAuthor', widget: 'relation', required: false, collection: 'authors', display_fields: ['name'], search_fields: ['name'], value_field: 'name', multiple: false, options_length: 20, hint: 'Leave blank to disable this setting.'}
  - label: 'Editorials'
    name: 'editorials'
    folder: 'assets/content/editorials'
    #slug: "{{fields.categories}}_{{slug}}_{{fields.author}}"
    format: 'json'
    extension: 'json'
    create: true
    identifier_field: headline
    preview_path: "/{{slug}}/"
    summary: "{{fields.headline}} ({{fields.author}}) [LTT{{fields.issue}}]"
    sortable_fields: ['headline', 'author', 'issue']
    view_filters:
      - label: 'Phil Goodwin'
        field: author
        pattern: 'Phil Goodwin'
      - label: 'Peter Stonham'
        field: author
        pattern: 'Peter Stonham'
    view_groups:
      - label: 'Author'
        field: author
    editor:
      preview: true
    fields:
      - {label: 'Publish Editorial Online?', name: 'published', widget: 'boolean', default: false}
      - {label: 'Allow User Comments?', name: 'allowComments', widget: 'boolean', default: true}
      - {label: 'Headline', name: 'headline', widget: 'string', required: true}
      - {label: 'Sub-Headline', name: 'subHeadline', widget: 'string', required: true, hint: 'Tip: An enticing sub-headline can be found from the blockquote inside the print publication edition.'}
      - {label: 'Categories', name: 'categories', widget: 'relation', required: true, hint: 'Multiple categories allowed.', collection: 'categories', display_fields: ['name'], search_fields: ['name'], value_field: 'name', multiple: true, options_length: 20}
      - {label: 'Author', name: 'author', widget: 'relation', required: true, collection: 'authors', display_fields: ['name'], search_fields: ['name'], value_field: 'name', multiple: false, options_length: 20}
      - {label: 'LTT Issue Number', name: 'issue', widget: 'number', value_type: 'int', min: 1, step: 1, required: false}
      - {label: 'Date Published', name: 'datePublished', widget: 'datetime', required: true, format: 'YYYY-MM-DD', date_format: 'Do MMMM YYYY', time_format: false}
      - {label: 'Body', name: 'body', widget: 'markdown', required: true, buttons: ['bold', 'italic', 'link', 'heading-three', 'quote', 'bulleted-list', 'numbered-list'], editor_components: ['image']}
